name: msc-joana
channels:
- defaults
dependencies:
- anaconda::tensorflow-gpu=2.4.1
- baal=1.3.2
- black=19.10b0
- conda-forge::cookiecutter_project_upgrader=1.3.1
- conda-forge::isort=5.10.1
- conda-forge::pandas-stubs=1.2.0.40
- conda-forge::pre-commit=2.16.0
- conda-forge::pytorch-lightning=1.5.8
- conda-forge::scikit-learn=1.0.2
- datasets=1.17.0
- fire=0.4.0
- flake8=4.0.1
- ipywidgets=7.6.5
- jupyterlab=3.2.1
- lightning-flash=0.6.0
- mypy=0.931
- mypy_extensions=0.4.3
- neptune-tensorflow-keras=0.9.9
- pandas=1.3.5
- pillow=8.4.0
- pip=21.2.4
- pyarrow=3.0.0
- pydocstyle=6.1.1
- python-decouple=3.4
- python=3.8
- pytorch::pytorch=1.8.1
- pytorch::torchaudio=0.8.1
- pytorch::torchvision=0.9.1
- seaborn=0.11.2
- sentencepiece=0.1.95
- tensorboard=2.6.0
- tensorflow-datasets=1.2.0
- tqdm=4.62.3
- transformers=4.14.1
- bioconda::pyfaidx
- conda-forge::wget